
/**
 * ***** DO NOT EDIT THIS FILE MANUALLY *****
 * This file is generated automatically by the Reaction
 * plugin loader and will be reset at each startup.
 */

import '/imports/plugins/core/accounts/client';
import '/imports/plugins/core/catalog/client';
import '/imports/plugins/core/checkout/client';
import '/imports/plugins/core/connectors/client';
import '/imports/plugins/core/dashboard/client';
import '/imports/plugins/core/dom/client';
import '/imports/plugins/core/email/client';
import '/imports/plugins/core/files/client';
import '/imports/plugins/core/i18n/client';
import '/imports/plugins/core/layout/client';
import '/imports/plugins/core/orders/client';
import '/imports/plugins/core/payments/client';
import '/imports/plugins/core/router/client';
import '/imports/plugins/core/shipping/client';
import '/imports/plugins/core/taxes/client';
import '/imports/plugins/core/templates/client';
import '/imports/plugins/core/ui/client';
import '/imports/plugins/core/ui-navbar/client';
import '/imports/plugins/core/ui-tagnav/client';
import '/imports/plugins/included/connectors-shopify/client';
import '/imports/plugins/included/default-theme/client';
import '/imports/plugins/included/discount-codes/client';
import '/imports/plugins/included/discount-rates/client';
import '/imports/plugins/included/inventory/client';
import '/imports/plugins/included/marketplace/client';
import '/imports/plugins/included/notifications/client';
import '/imports/plugins/included/payments-authnet/client';
import '/imports/plugins/included/payments-braintree/client';
import '/imports/plugins/included/payments-example/client';
import '/imports/plugins/included/payments-paypal/client';
import '/imports/plugins/included/payments-stripe/client';
import '/imports/plugins/included/product-admin/client';
import '/imports/plugins/included/product-detail-simple/client';
import '/imports/plugins/included/product-variant/client';
import '/imports/plugins/included/search-mongo/client';
import '/imports/plugins/included/shipping-rates/client';
import '/imports/plugins/included/shipping-shippo/client';
import '/imports/plugins/included/sms/client';
import '/imports/plugins/included/social/client';
import '/imports/plugins/included/taxes-avalara/client';
import '/imports/plugins/included/taxes-taxcloud/client';
import '/imports/plugins/included/taxes-taxjar/client';
import '/imports/plugins/included/ui-search/client';
import '/imports/plugins/custom/bedding-builder/client';
import '/imports/plugins/custom/blog-links/client';
import '/imports/plugins/custom/color-houses/client';
import '/imports/plugins/custom/colors/client';
import '/imports/plugins/custom/flaneur/client';
import '/imports/plugins/custom/flaneur-theme/client';
import '/imports/plugins/custom/main-menu/client';
import '/imports/plugins/custom/pages/client';
import '/imports/plugins/custom/recommends/client';
import '/imports/plugins/custom/supply-chain/client';
import '/imports/plugins/custom/swatchbook/client';
