import './templates/colorHouseActionButtons.html';
import './templates/colorHouseActionButtons';
import './templates/colorHouses.html';
import './templates/colorHouses';
import './templates/manageColorHouses.html';
import './templates/manageColorHouses';
import '../lib/collections';
import '../lib/tables';
import './less/colorHouses.less';
